# Generated by Django 4.2 on 2023-06-06 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='addonsGambarDua',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='addonsGambarSatu',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='addonsGambarTiga',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('P', 'Paypal'), ('C', 'COD')], max_length=1),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('T', 'Tops'), ('P', 'Pants'), ('A', 'Accessories')], max_length=2),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('komentar', models.TextField()),
                ('produk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.produkitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
    ]
