# Generated by Django 4.2 on 2023-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='harga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='harga_diskon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
